<?php require('template/header.phtml') ;

require_once('Models/AccessibilityData.php'); ?>

<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>

	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
		<li class="active">Accessibility</li>
	</ol>		

    <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="sitemap.php">Site Map</a>
                            <br><br>
                            <a href="accessibility.php">Accessibility</a>
                            <br><br>
                            <a href="privacypolicy.php">Privacy Policy</a>
                            <br><br>
                            <a href="foi.php">FOI Request</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->
    
    
    
    <div class="row">
        <div class="col-md-10">
        
        <h1>Accessibility</h1>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getaccessibility() .'</p>' ;} ?>

        <h2>Features</h2>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getfeatures() .'</p>' ;} ?>

        <h3>Structure</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getstructure() .'</p>' ;} ?>

        <h3>Navigation</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getnavigation() .'</p>' ;} ?>

        <h3>Text sizes</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->gettextsizes() .'</p>' ;} ?>

        <h3>Links</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getlinks() .'</p>' ;} ?>

        <h3>Images</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getimages() .'</p>' ;} ?>

        <h3>Colour</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getcolour() .'</p>' ;} ?>

        <h3>Forms</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getforms() .'</p>' ;} ?>

        <h3>New windows</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getnewwindows() .'</p>' ;} ?>

        <h3>Audio and video</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getaudioandvideo() .'</p>' ;} ?>

        <h3>JavaScript</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getjavaScript() .'</p>' ;} ?>

        <h3>Alternative text pages</h3>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getalternativetextpages() .'</p>' ;} ?>

        <h2>Standards compliance</h2>

        <?php foreach($view->accessibilityDataSet as $accessibilityData) {
              echo '<p>'. $accessibilityData->getstandardscompliance() .'</p>' ;} ?>

        </div>
    </div>
    
    

</div>
<!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>
