<?php require('template/header.phtml') ;

require_once('Models/AerospaceData.php'); ?>

<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>
    <br>
    
	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
                <li><a href="msccourses.php">MSc Courses</a></li>
		<li class="active">Aerospace Engineering</li>
	</ol> 
    
            <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="taughtdegrees.php">Taught Degrees</a>
                            <br><br>
                            <a href="applying.php">Applying</a>
                            <br><br>
                            <a href="applyingnext.php">Applying Next</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->
    
    <h1>Aerospace Engineering MSc/PgDip/PgCert</h1>     

      
    <div class="col-md-10">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
            <li><a href="#coursedetails" data-toggle="tab">Course Details</a></li>
            <li><a href="#entry" data-toggle="tab">Entry Requirements</a></li>
            <li><a href="#teaching" data-toggle="tab">Teaching</a></li>
            <li><a href="#employability" data-toggle="tab">Employability</a></li>
            <li><a href="#feesandfunding" data-toggle="tab">Fees and Funding</a></li>
            <li><a href="#facilities" data-toggle="tab">Facilities</a></li>
        </ul>
    
    <div class="tab-content">
        <div class="tab-pane active" id="overview">
            <br>
            
             <div class="row">
                <div class="col-md-12">
                        <div class="panel-body text-center">
                            <div class="fa fa-plane fa-2x"></div> International Students can apply 
                        </div>
                </div>
            </div>
            
            <br>
            
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                      <h3 class="panel-title">3 good reasons to study Aerospace Engineering at Salford:</h3>
                    </div>
                    <div class="panel-body">
                        <ul><li>Great employer demand for graduates of this course</li></ul>
                        <ul><li>Access to excellent facilities including over 20 wind tunnels and a DC10 jet engine<br></li></ul>
                        <ul><li>Accredited course by the Institute of Mechanical Engineers, giving you the opportunity to achieve chartered engineer status</li></ul>
                    </div>
                </div>
                </div>
            </div>
            
           
        
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading"><b>Key Information</b></div>
                            <div class="panel-body">
                                <strong>Start Dates: </strong>
                                September
                                <br><br>
                                <strong>Duration: </strong><br><br>
                                <strong>MSc</strong> (one year full-time)<br>
                                <strong>PgDip</strong> (nine months full-time)
                            </div>
                      </div>
                    <blockquote><p><em>94%</em> of our postgraduates go on to employment and/or further study within six months of graduating.</p><cite>DLHE 2009 and 2010</cite></blockquote>
                </div>
            
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading"><b>Course Summary</b></div>
                            <div class="panel-body">
                     <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
                            echo ''. $aerospaceEngineeringData->getcourse() .'' ;} ?>      

                            </div>
                      </div>
                </div>     
            </div>
        </div>
        <div class="tab-pane" id="coursedetails">
            <h3>Course Details</h3>


  <h3>Full-time study option:</h3>

    <h4>Semester 1</h4>

    <p>Choose one of the following:</p>

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Aerodynamics (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails1() .'' ;} ?> 
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Finite Element Analysis (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails2() .'' ;} ?> 
    </div>
      </div>
    </div>
  
      </div>

  <h4>Semester 2</h4>

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Aerospace Assembly (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails3() .'' ;} ?> 
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Flight Dynamics and Control (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails4() .'' ;} ?> 
    </div>
      </div>
    </div>
      </div>

   <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Flight Simulation (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails5() .'' ;} ?> 
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">MSc Project and Dissertation (60 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getcoursedetails6() .'' ;} ?> 
    </div>
      </div>
    </div>
      </div> 
  
        </div>
        
        
        <div class="tab-pane" id="entry">
             <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getentry() .'' ;} ?> 

        </div>
      
        
        <div class="tab-pane" id="teaching">
            <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getteaching() .'' ;} ?> 
        
        </div>
        
        <div class="tab-pane" id="employability">
           <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getemployability() .'' ;} ?> 
             <br><br><br>
        </div>
        
        <div class="tab-pane" id="feesandfunding">
            <div class="col-md-6">
                <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getfeesandfunding() .'' ;} ?> 
            </div>
        </div>
        
        
        <div class="tab-pane" id="facilities">
           <?php foreach($view->aerospaceDataSet as $aerospaceEngineeringData) {
              echo ''. $aerospaceEngineeringData->getfacilities() .'' ;} ?>   

        </div>
            
        
      
        </div><!-- tab content -->
    </div>
    
</div><!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>