<?php require('template/header.phtml') ?>


<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>


    <ol class="breadcrumb">
        <li><a href="index.php">Home</a></li>	
        <li class="active">Contact Us</li>
    </ol>		

    <h1>Contact Us</h1>     




    <div class="row">
        <div class="col-md-3">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><b>Address</b></h4>
                </div>
                <div class="panel-body">
                    <address>
                        The School of Computing, Science & Engineering<br>
                        Newton Building<br>
                        University of Salford<br>
                        Salford <br>
                        Greater Manchester<br>
                        M5 4WT<br>
                        UK
                    </address>
                </div>
            </div>		
        </div>


        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><strong>Course and Admission Enquiries</strong></h4>
                </div>
                <div class="panel-body">
                    <p><strong>Undergraduate and postgraduate taught:</strong><br>
                        UK/EU students:<br>
                        +44 (0)161 295 4545<br>
                        <a href="mailto:course-enquiries@salford.ac.uk">course-enquiries@salford.ac.uk</a></p>
                </div>
            </div>
        </div>


        <div class="col-md-3">   
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><strong>International</strong></h4>
                </div>
                <div class="panel-body">
                    <p><strong>International/non-EU students:</strong><br>
                        +44 (0)161 295 4545<br>
                        <a href="mailto:international@salford.ac.uk">international@salford.ac.uk</a></p>
                </div>
            </div>

        </div>


        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title"><strong>General enquiries</strong></h4>
                </div>
                <div class="panel-body">
                    <p><strong>School Office</strong>:<br>
                        +44(0)161 295 3223<br>
                        <a href="mailto:cse-programme-admin@salford.ac.uk">cse-programme-admin@salford.ac.uk</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
        <div class="map" id="map_canvas">
            <iframe class=" img img-responsive img-responsive1" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2374.026928915863!2d-2.273926800000022!3d53.48584865000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487bae25b08332cf%3A0x61a1ab6bc06a247a!2sNewton+Bldg%2C+University+of+Salford%2C+Salford+M5+4NT!5e0!3m2!1sen!2suk!4v1425561266540" width="1140" frameborder="0" style="border:0"></iframe>
        </div>
        </div>
    </div>


</div>
<!-- /container -->  


<?php require('template/footer.phtml') ?>

