<?php require('template/header.phtml') ;

require_once('Models/FoiData.php'); ?>

<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>
    
	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
		<li class="active">FOI Request</li>
	</ol>		

    <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="sitemap.php">Site Map</a>
                            <br><br>
                            <a href="accessibility.php">Accessibility</a>
                            <br><br>
                            <a href="privacypolicy.php">Privacy Policy</a>
                            <br><br>
                            <a href="foi.php">FOI Request</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->

    
    <div class="row">
        <div class="col-md-10">

            <h1>FOI Request</h1>

            <h2>How to make a Freedom of Information Request</h2>

            <?php foreach($view->foiDataSet as $foiData) {
              echo '<p>'. $foiData->getinfo1() .'</p>' ;} ?>

            <h2>Request for information relating to yourself</h2>

            <?php foreach($view->foiDataSet as $foiData) {
              echo '<p>'. $foiData->getinfo2() .'</p>' ;} ?>

            <h2>More information</h2>

            <p><a href="http://www.infogov.salford.ac.uk/freedom/" target="blank">More information about Freedom of Information at the University of Salford.</a>

        </div>
    </div>
    
</div>
<!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>
