<?php require('template/header.phtml') ;

require_once('Models/GasEngineeringData.php'); ?>

<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>
    <br>
    
	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
                <li><a href="msccourses.php">MSc Courses</a></li>
		<li class="active">Gas Engineering and Management</li>
	</ol> 
    
            <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="taughtdegrees.php">Taught Degrees</a>
                            <br><br>
                            <a href="applying.php">Applying</a>
                            <br><br>
                            <a href="applyingnext.php">Applying Next</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->
    
    <h1>Gas Engineering and Management MSc/PgDip</h1>     

  
    <div class="col-md-10">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
            <li><a href="#coursedetails" data-toggle="tab">Course Details</a></li>
            <li><a href="#entry" data-toggle="tab">Entry Requirements</a></li>
            <li><a href="#teaching" data-toggle="tab">Teaching</a></li>
            <li><a href="#employability" data-toggle="tab">Employability</a></li>
            <li><a href="#feesandfunding" data-toggle="tab">Fees and Funding</a></li>
        </ul>
    
    <div class="tab-content">
        <div class="tab-pane active" id="overview">
            <br>
            
            <div class="row">
                <div class="col-md-12">
                        <div class="panel-body text-center">
                            <i class="fa fa-clock-o fa-2x"></i> Part Time &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="fa fa-calendar fa-2x"></i> Alternative start dates available &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="fa fa-plane fa-2x"></i> International Students can apply &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                </div>
            </div>
            
            <br>
            
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                      <h3 class="panel-title">3 good reasons to study Gas Engineering and Management at Salford:</h3>
                    </div>
                    <div class="panel-body">
                        <ul><li>Flexible but rigorous period of study for graduates working in, or intending to work in, the natural gas/oil industry</li></ul>
                        <ul><li>Accredited by the Institution of Gas Engineers and Managers (IGEM).<br></li></ul>
                        <ul><li>Excellent employment prospects</li></ul>
                    </div>
                </div>
                </div>
            </div>
            
            
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading"><b>Key Information</b></div>
                        <div class="panel-body">
                            <strong>Start Dates: </strong>
                            September; January
                            <br><br>
                            <strong>Duration: </strong><br><br>
                            <strong>September intake</strong>
                            <p>MSc (one year full-time or two years part-time)<br>
                            PgDip (nine months full-time or one year and six months part-time)</p>

                            <strong>January intake</strong>

                            <p>MSc (one year and four months full-time or two years and eight months distance learning / part-time)<br>
                            PgDip (one year full-time or two years distance learning / part-time)</p>
                        </div>
                  </div>
            </div>
            
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading"><b>Course Summary</b></div>
                        <div class="panel-body">
                             <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcourse() .'' ;} ?>                           
                        </div>
                  </div>
            </div>     
        </div>
        </div>
        
        
        <div class="tab-pane" id="coursedetails">
            <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails() .'' ;} ?>

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Fundamentals of Natural Gas and Production Systems and Design (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails1() .'' ;} ?>
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Experimental and Measurement Methods (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails2() .'' ;} ?>
    </div>
      </div>
    </div>  
      </div>
  

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Business and Project Gas Management (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails3() .'' ;} ?>
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Utilisation of Natural Gas (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails4() .'' ;} ?>
    </div>
      </div>
    </div>
      </div>


  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Distribution and Transmission Systems and design of Natural Gas (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails5() .'' ;} ?>
    </div>
      </div>
    </div>
      
      <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Gas flow and network analysis (15 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails6() .'' ;} ?>
    </div>
      </div>
    </div>
  </div>  
  
  <div class="row">
    <div class="col-md-12">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">MSc Project (60 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getcoursedetails7() .'' ;} ?>
    </div>
      </div>
    </div>
  </div>

        </div>
        
        
        <div class="tab-pane" id="entry">
             <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getentry() .'' ;} ?>

        </div>
      
        
        <div class="tab-pane" id="teaching">
            <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getteaching() .'' ;} ?>
        
        </div>
        
        <div class="tab-pane" id="employability">
            <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getemployability() .'' ;} ?>     
             
        </div>
        
        <div class="tab-pane" id="feesandfunding">
            <div class="col-md-6">
                <?php foreach($view->gasEngineeringDataSet as $gasEngineeringData) {
                        echo ''. $gasEngineeringData->getfeesandfunding() .'' ;} ?>
            </div>
        </div>
        
        
            
        
      
        </div><!-- tab content -->
    </div>    
    
</div><!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>