<?php require('template/header.phtml') ;

require_once('Models/CombustionEngineeringData.php'); ?>
<!-- container -->  
<div class="container"> 
    <br>
    <br>
    <br>
    <br>
    <br>
    
	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
                <li><a href="msccourses.php">MSc Courses</a></li>
		<li class="active">Industrial and Commercial Combustion Engineering</li>
	</ol> 
    
            <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="taughtdegrees.php">Taught Degrees</a>
                            <br><br>
                            <a href="applying.php">Applying</a>
                            <br><br>
                            <a href="applyingnext.php">Applying Next</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->
    
    <h1>Industrial and Commercial Combustion Engineering MSc/PgDip/PgCert</h1>     

      
    <div class="col-md-10">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
            <li><a href="#coursedetails" data-toggle="tab">Course Details</a></li>
            <li><a href="#entry" data-toggle="tab">Entry Requirements</a></li>
            <li><a href="#teaching" data-toggle="tab">Teaching</a></li>
            <li><a href="#employability" data-toggle="tab">Employability</a></li>
            <li><a href="#feesandfunding" data-toggle="tab">Fees and Funding</a></li>
        </ul>
    
    <div class="tab-content">
        <div class="tab-pane active" id="overview">
            <br>
            
            <div class="row">
                <div class="col-md-12">
                        <div class="panel-body text-center">
                            <div class="fa fa-home fa-2x"></div> Distance Learning &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="fa fa-plane fa-2x"></div> International Students can apply &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                </div>
            </div>
            
            <br>
            
            <div class="row">
                <div class="col-md-12">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                      <h3 class="panel-title">3 good reasons to study Industrial and Commercial Combustion Engineering at Salford:</h3>
                    </div>
                    <div class="panel-body">
                        <ul><li>A specialist qualification that is recognised by industry experts</li></ul>
                        <ul><li>Taught by distance e-learning so you can fit in study around your work<br></li></ul>
                        <ul><li>The first course in the UK to specialise in combustion engineering at a commercial level.</li></ul>
                    </div>
                </div>
                </div>
            </div>
            
            
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading"><b>Key Information</b></div>
                            <div class="panel-body">
                                <strong>Start Dates: </strong>
                                September
                                <br><br>
                                <strong>Duration: </strong><br><br>
                                <p>MSc (three years distance e-learning)<br>
                                PgDip (one year distance e-learning)<br>
                                PgCert (one year distance e-learning)</p>
                            </div>
                      </div>
                </div>

                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading"><b>Course Summary</b></div>
                            <div class="panel-body">
                           <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                            echo ''. $combustionEngineeringData->getcourse() .'' ;} ?>    
                            </div>
                      </div>
                </div>     
            </div>
        </div>
        <div class="tab-pane" id="coursedetails">
            
        <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails() .'' ;} ?>
     

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Combustion Theory and Burner Design (30 credits)</h3>
    </div>
    <div class="panel-body">
         <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails1() .'' ;} ?>
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Burner Utilisation and Process Control (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails2() .'' ;} ?>
    </div>
      </div>
    </div>
      </div>
  

  <div class="row">
    <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Industrial Gas Safety and Regulations (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails3() .'' ;} ?>
    </div>
      </div>
    </div>


     <div class="col-md-6">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Industrial Burner Commissioning and Optimisation (30 credits)</h3>
    </div>
    <div class="panel-body">
        <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails4() .'' ;} ?>
    </div>
      </div>
    </div>
      </div>


  <div class="row">
    <div class="col-md-12">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Dissertation (60 credits)</h3>
    </div>
    <div class="panel-body">
                <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getcoursedetails5() .'' ;} ?>
    </div>
      </div>
    </div>
  
  </div>

        </div>
        
        
        <div class="tab-pane" id="entry">
             <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getentry() .'' ;} ?>     

        </div>
      
        
        <div class="tab-pane" id="teaching">
            <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getteaching() .'' ;} ?>
            
        </div>
        
        <div class="tab-pane" id="employability">
            <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getemployability() .'' ;} ?>
             
        </div>
        
        <div class="tab-pane" id="feesandfunding">
            
            <?php foreach($view->combustionEngineeringDataSet as $combustionEngineeringData) {
                        echo ''. $combustionEngineeringData->getfeesandfunding() .'' ;} ?>

            </div>
        
        
      
        </div><!-- tab content -->
    </div>
    
</div><!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>