<?php require('template/header.phtml') ?>

<div>
         <!-- Header -->
            <header id="head">
                <img src="images/courses.png" class ="img img-responsive">
            </header>
        <!-- /Header -->
    </div>
        
<!-- container -->  
<div class="container">         
    <ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
		<li class="active">MSc Courses</li>
    </ol>		

    <h1>MSc Courses</h1>
            
            <h2>Acoustics, Audio and Video</h2>
            
            <div class="row">
                <div class="col-sm-3">
                    <a href="acoustics.php" class="thumbnail thumbnailcustom">
                        <img src="images/acoustics.png" alt="Acoustics"> 
                    <div class="caption">
                      <h4>Acoustics</h4>
                    </div>
                     </a>
                </div>

                   <div class="col-sm-3">
                    <a href="audio-production.php" class="thumbnail thumbnailcustom">
                    <img src="images/audioproduction.png" alt="Audio Production">
                    <div class="caption">
                      <h4>Audio Production</h4>
                    </div>
                     </a>
                </div>
            
                
              </div>
            
            <h2>Aeronautical Engineering</h2>
            
            <div class="row">
                <div class="col-sm-3">
                    <a href="aerospace-engineering.php" class="thumbnail thumbnailcustom">
                    <img src="images/aero-engineering.png" alt="Aerospace Engineering">
                    <div class="caption">
                      <h4>Aerospace Engineering</h4>
                    </div>
                     </a>
                </div>
              </div>
           
            <h2>Civil and Structural Engineering</h2>
            
            <div class="row">
                <div class="col-sm-3">
                    <a href="structural-engineering.php" class="thumbnail thumbnailcustom">
                    <img src="images/structural-engineering.png" alt="Structural Engineering">
                    <div class="caption">
                      <h4>Structural Engineering</h4>
                    </div>
                     </a>
                </div>
                   
                   <div class="col-sm-3">
                    <a href="transport-engineering-and-planning.php" class="thumbnail thumbnailcustom">
                    <img src="images/transport.png" alt="Transport Engineering and Planning">
                    <div class="caption">
                      <h4>Transport Engineering and Planning</h4>
                    </div>
                     </a>
                </div>
              </div>
            
            <h2>Computer Networking and Telecommunications</h2>
            
            <div class="row">
                <div class="col-sm-3">
                  <a href="data-telecommunications-networks.php" class="thumbnail thumbnailcustom">
                    <img src="images/data-network.png" alt="Data Telecommunications Networks">
                    <div class="caption">
                      <h4>Data Telecommunications Networks</h4>
                    </div>
                  </a>
                </div>
            </div>

            <h2>Computer Science</h2>
            
            <br>
            
            <div class="row">
             <div class="col-sm-3">
                  <a href="databases-and-web-based-systems.php" class="thumbnail thumbnailcustom">
                    <img src="images/databases-web.png" alt="Databases and Web-based Systems">
                    <div class="caption">
                      <h4>Databases and Web-based Systems</h4>
                    </div>
                     </a>
                </div>
             

               </div>
            
            <h2>Petroleum and Gas Engineering</h2>
            
               <div class="row">
                <div class="col-sm-3">
                    <a href="gas-engineering-and-management.php" class="thumbnail thumbnailcustom">
                    <img src="images/gas.png" alt="Gas Engineering and Management">
                    <div class="caption">
                      <h4>Gas Engineering and Management</h4>
                    </div>
                     </a>
                </div>

                   
                   <div class="col-sm-3">
                    <a href="industrial-and-commercial-combustione-engineering.php" class="thumbnail thumbnailcustom">
                    <img src="images/combustion-engineering.png" alt="Industrial and Commercial Combustion Engineering">
                    <div class="caption">
                      <h4>Industrial and Commercial Combustion Engineering</h4>
                    </div>
                     </a>
                </div>
                         
                <div class="col-sm-3">
                    <a href='petroleum-and-gas-engineering.php' class="thumbnail thumbnailcustom">
                    <img src="images/petroleum.png" alt="Petroleum and Gas Engineering">
                    <div class="caption">
                      <h4>Petroleum and Gas Engineering</h4>
                    </div>
                  </a>
                </div>
              </div>
            
            
            <h2>Robotics and System Engineering</h2>
            
            <div class="row">
                <div class="col-sm-3">
                    <a href="advanced-control-systems.php" class="thumbnail thumbnailcustom">
                    <img src="images/control-system.png" alt="Advanced Control Systems">
                    <div class="caption">
                      <h4>Advanced Control Systems</h4>
                    </div>
                     </a>
                </div>

                   
                   <div class="col-sm-3">
                    <a href="robotics-and-automation.php" class="thumbnail thumbnailcustom">
                    <img src="images/robotics.png" alt="Robotics and Automation">
                    <div class="caption">
                      <h4>Robotics and Automation</h4>
                    </div>
                     </a>
                </div>
            </div>
            
            
</div>
        

<?php require('template/footer.phtml') ?>
