<?php require('template/header.phtml') ?>

<!-- container -->  
<div class="container"> 
    <header id="head" class="secondary"></header>
    
    
	<ol class="breadcrumb">
		<li><a href="index.php">Home</a></li>	
		<li class="active">Site Map</li>
	</ol>		

    <!-- Sidebar -->
		
        <aside class="col-md-2 sidebar sidebar-left">
            
		<div class="row widget">
			<div class="col-xs-12">
                            <a href="sitemap.php">Site Map</a>
                            <br><br>
                            <a href="accessibility.php">Accessibility</a>
                            <br><br>
                            <a href="privacypolicy.php">Privacy Policy</a>
                            <br><br>
                            <a href="privacypolicy.php">FOI Request</a>
			</div>
		</div>
	</aside>
    <!-- /Sidebar -->
    
    <h1>Site Map</h1>
    
    <div class="col-md-10">
        
        <div class="sitemap">
            <ul>
		<li><a href="http://www.salford.ac.uk/study" title="Study">Study</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate" title="Undergraduate study">Undergraduate study</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford" title="Why study at Salford">Why study at Salford</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford/location2" title="Location">Location</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford/mediacityuk2" title="MediaCityUK">MediaCityUK</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford/teaching-quality" title="Teaching quality">Teaching quality</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford/job-prospects" title="Job prospects">Job prospects</a>
			</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/why-study-at-salford/case-studies" title="Salford stories">Salford stories</a></li>
            </ul>
		</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/life-at-salford" title="Life at Salford">Life at Salford</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters" title="Fees and funding">Fees and funding</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters/tuition-fees-and-loans" title="Tuition fees and loans">Tuition fees and loans</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters/maintenance-loans-and-grants" title="Maintenance loans and grants">Maintenance loans and grants</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters/repayment" title="Repayment">Repayment</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters/students-on-healthcare-and-social-work-courses" title="Students on healthcare and social work courses ">Students on healthcare and social work courses </a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/money-matters/scholarships-and-bursaries" title="Scholarships and bursaries">Scholarships and bursaries</a></li>
            </ul>
		</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/accomodation" title="Accommodation">Accommodation</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying" title="Applying">Applying</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/before-you-apply" title="Before you apply">Before you apply</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/entry-requirements" title="Entry requirements">Entry requirements</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/how-to-apply" title="How to apply">How to apply</a>
            <ul>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/how-to-apply/ucas-applications" title="UCAS applications">UCAS applications</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/how-to-apply/part-time-courses" title="Part-time courses">Part-time courses</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/how-to-apply/second-or-final-year-entry" title="Second or final year entry">Second or final year entry</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/how-to-apply/international-applications" title="International applications">International applications</a></li>
            </ul>
		</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/applied-what-next" title="Applied - what next">Applied - what next</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/applying/joining-checklist" title="Joining checklist">Joining checklist</a></li>
            </ul>
		</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/information-for-parents-and-guardians" title="For parents and carers">For parents and carers</a>
            <ul>
            	<li><a href="http://www.salford.ac.uk/study/undergraduate/information-for-parents-and-guardians/parents" title="Choosing Salford">Choosing Salford</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/information-for-parents-and-guardians/university-living" title="University living">University living</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/information-for-parents-and-guardians/student-finance" title="Student finance">Student finance</a></li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/information-for-parents-and-guardians/frequently-asked-questions" title="Frequently asked questions">Frequently asked questions</a></li>
            </ul>
		</li>
		<li><a href="http://www.salford.ac.uk/study/undergraduate/schools-and-colleges" title="For schools and colleges">For schools and colleges</a>
            <ul>
			<li><a href="http://www.salford.ac.uk/study/undergraduate/schools-and-colleges/post-16" title="Post-16">Post-16</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/undergraduate/schools-and-colleges/teachers-and-advisors" title="Teachers and advisers">Teachers and advisers</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/undergraduate/schools-and-colleges/teachers-and-advisors/conference-for-teachers" title="conference-for-teachers">conference-for-teachers</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/undergraduate/salford-alternative-entry-scheme" title="Salford Alternative Entry Scheme form">Salford Alternative Entry Scheme form</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate" title="Postgraduate study">Postgraduate study</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/postgraduate/taught" title="Taught degrees">Taught degrees</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/research" title="Research degrees">Research degrees</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/salford-stories" title="Salford stories">Salford stories</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/flexible-start-dates" title="Flexible start dates">Flexible start dates</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/life-at-salford" title="Life at Salford">Life at Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/why-study-at-salford" title="Why study at Salford">Why study at Salford</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/postgraduate/why-study-at-salford/location2" title="Location">Location</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/why-study-at-salford/mediacityuk2" title="MediaCityUK">MediaCityUK</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding" title="Fees and funding">Fees and funding</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/taught-course-fees-and-funding" title="Taught course fees and funding">Taught course fees and funding</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/research-degree-fees-and-funding" title="Research degree fees and funding">Research degree fees and funding</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/funded-phd-studentship" title="PhD studentships">PhD studentships</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/funded-phd-studentship/pathway-to-excellence-studentships" title="Pathway to Excellence studentships">Pathway to Excellence studentships</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/funded-phd-studentship/gts" title="Graduate Teaching Studentships">Graduate Teaching Studentships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/fees-and-funding/ahrc-studentships" title="AHRC studentships">AHRC studentships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/applying" title="Applying">Applying</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/postgraduate/applying/applying-for-taught-courses" title="Applying for taught courses">Applying for taught courses</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/applying/applying-for-research" title="Applying for research ">Applying for research </a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/applying/applied-what-next" title="Applied what next">Applied what next</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/postgraduate/applying/policy-statement-on-equality-and-diversity" title="Policy statement on equality and diversity">Policy statement on equality and diversity</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford" title="Life at Salford">Life at Salford</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/life-at-salford/our-location" title="University of Salford location">University of Salford location</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/life-at-salford/our-location/city-life" title="City life">City life</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/our-location/the-north-west" title="The North West">The North West</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/our-location/local-shops-and-services" title="Local shops and services">Local shops and services</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/campus-and-facilities" title="Campus and facilities">Campus and facilities</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/accommodation" title="Accommodation">Accommodation</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/leisure-and-entertainment" title="Leisure and entertainment">Leisure and entertainment</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/campus-sports-and-activities" title="Campus sports and activities">Campus sports and activities</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/life-at-salford/student-support" title="Student support">Student support</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/life-at-salford/student-support/academic-life" title="Academic life">Academic life</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit" title="Visit us">Visit us</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/visit/undergraduate-open-days" title="Undergraduate open days">Undergraduate open days</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit/applicant-visit-days" title="UG applicant visit days">UG applicant visit days</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit/postgraduate-open-days" title="Postgraduate open days">Postgraduate open days</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/study/visit/postgraduate-open-days/postgraduate-open-day-schedule-rename-this-when-active" title="Postgraduate Open Day Schedule">Postgraduate Open Day Schedule</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit/ucas-fairs" title="UCAS fairs 2015">UCAS fairs 2015</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit/postgraduate-fairs" title="Postgraduate fairs">Postgraduate fairs</a>
			</li>
						<li><a href="http://www.salford.ac.uk/study/visit/european-fairs" title="European fairs">European fairs</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/study/international-students" title="International students">International students</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international" title="International">International</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/countries" title="Countries">Countries</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/uk-based-international-students" title="UK-Based International Students">UK-Based International Students</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/english-language-centre" title="English Language Centre">English Language Centre</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/english-language-centre/why-choose-salford" title="Why choose Salford">Why choose Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/english-language-centre/our-courses" title="Our courses">Our courses</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/english-language-centre/what-next" title="What next">What next</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners" title="Education partners">Education partners</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/education-partners/undergraduate-partners" title="Undergraduate partners">Undergraduate partners</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/education-partners/undergraduate-partners/ncuk" title="NCUK">NCUK</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners/undergraduate-partners/ncc-education" title="NCC Education">NCC Education</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners/undergraduate-partners/new-college-manchester" title="New College Manchester">New College Manchester</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners/undergraduate-partners/edexcel" title="Edexcel">Edexcel</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners/postgraduate-partners" title="Postgraduate partners">Postgraduate partners</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/education-partners/postgraduate-partners/robert-kennedy-college" title="Robert Kennedy College">Robert Kennedy College</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-partners/postgraduate-partners/estia" title="ESTIA">ESTIA</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/education-consultants" title="Education consultants">Education consultants</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/international-sponsor-partnerships" title="International sponsor partnerships">International sponsor partnerships</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/science-without-borders" title="Science Without Borders">Science Without Borders</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/science-without-borders/postgraduate-study" title="Postgraduate research - Science without Borders">Postgraduate research - Science without Borders</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/international-sponsor-partnerships/dikti-scholarships" title="DIKTI scholarships">DIKTI scholarships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/semester-study-abroad" title="Semester study abroad">Semester study abroad</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/semester-study-abroad/entry-requirements-fees-and-study-options" title="Entry requirements, fees and study options">Entry requirements, fees and study options</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/faqs" title="Frequently Asked Questions">Frequently Asked Questions</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/faqs/scholarships-faq" title="Scholarships FAQ">Scholarships FAQ</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/our-students" title="Our students">Our students</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/meet-us" title="Meet us">Meet us</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/life-at-salford" title="Life at Salford">Life at Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/starting-at-university" title="Starting at University">Starting at University</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/careers-and-employability" title="Careers and Employability">Careers and Employability</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/how-to-apply" title="How to apply">How to apply</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/international/how-to-apply/joining-checklist" title="Joining checklist">Joining checklist</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/how-to-apply/portfolio-support" title="Portfolio support">Portfolio support</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/international/entry-requirements" title="Entry requirements">Entry requirements</a>
			</li>
						<li><a href="http://www.salford.ac.uk/international/immigration-and-visas" title="Immigration and Visas">Immigration and Visas</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research" title="Research">Research</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/ref-2014" title="REF 2014">REF 2014</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/our-vision" title="Our vision">Our vision</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/our-vision/research-in-our-colleges-and-schools" title="Research in our Colleges and Schools">Research in our Colleges and Schools</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-performance" title="Research performance">Research performance</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact" title="Impact">Impact</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/impact/case-studies" title="Our Impact">Our Impact</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/impact/case-studies/business-and-economy" title="Business and Economy">Business and Economy</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/case-studies/culture-and-media" title="Culture and Media">Culture and Media</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/case-studies/environment-and-sustainability" title="Environment and Sustainability">Environment and Sustainability</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/case-studies/health-and-wellbeing" title="Health and Wellbeing">Health and Wellbeing</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/case-studies/science,-technology-and-digital" title="Science, Technology and Digital">Science, Technology and Digital</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/case-studies/social-policy-and-communities" title="Social Policy and Communities">Social Policy and Communities</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/building-the-picture-of-salford-impact" title="Building the picture of Salford Impact">Building the picture of Salford Impact</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/research-excellence-framework-2014" title="Research Excellence Framework 2014">Research Excellence Framework 2014</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/impact/impact-application-funding" title="Impact in applications for funding">Impact in applications for funding</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/concordat" title="Researcher development">Researcher development</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management" title="Research data management">Research data management</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/research-data-management/policy" title="Progress and policy">Progress and policy</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management/planning" title="Planning">Planning</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management/safedata" title="Keeping data safe">Keeping data safe</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management/sharing" title="Sharing &amp; re-using data">Sharing &amp; re-using data</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management/archiving" title="Archiving data">Archiving data</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-data-management/funder" title="Funder expectations">Funder expectations</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/perspectives-magazine" title="Perspectives Magazine">Perspectives Magazine</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/perspectives-magazine/subscribe" title="Subscribe to Perspectives">Subscribe to Perspectives</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/perspectives-magazine/archive" title="Archive">Archive</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/research-centres" title="Research centres">Research centres</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/research-centres/facilities" title="Facilities">Facilities</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research" title="Postgraduate research">Postgraduate research</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/postgraduate-research/applying2" title="Applying">Applying</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/funding-and-scholarships2" title="Funding and scholarships">Funding and scholarships</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/our-community" title="Get involved">Get involved</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/postgraduate-research/our-community/phd-student-in-acoustics-jenna-condie" title="PhD Student - Acoustics - Jenna Condie">PhD Student - Acoustics - Jenna Condie</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/our-community/phd-student-in-health-sciences-jon-radcliffe" title="PhD Student - Health Sciences - Jon Radcliffe">PhD Student - Health Sciences - Jon Radcliffe</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/our-community/mphil-student-health-sciences-rachel-allen" title="MPhil Student - Health Sciences - Rachel Allen">MPhil Student - Health Sciences - Rachel Allen</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/our-community/phd-student-law-chrissie-patman" title="PhD Student - Law - Chrissie Patman">PhD Student - Law - Chrissie Patman</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/sparc" title="SPARC">SPARC</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/postgraduate-research/sparc/sparc-2012" title="SPARC 2012">SPARC 2012</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/postgraduate-research/sparc/sparc-2011" title="SPARC 2011">SPARC 2011</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/research/conferences" title="Conferences">Conferences</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/news" title="Research News">Research News</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/events" title="Research Events">Research Events</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research" title="Policy solutions">Policy solutions</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/research/policy-research/business,-innovation-and-skills" title="Business, innovation and skills">Business, innovation and skills</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research/communities-and-local-government" title="Communities and local government">Communities and local government</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research/energy-and-climate-change" title="Energy and climate change">Energy and climate change</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research/health" title="Health">Health</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research/home-affairs-and-justice" title="Home affairs and justice">Home affairs and justice</a>
			</li>
						<li><a href="http://www.salford.ac.uk/research/policy-research/about-sipp" title="About the Salford Institute for Public Policy">About the Salford Institute for Public Policy</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business" title="Working with Business">Working with Business</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/training-and-cpd" title="Training-and-CPD">Training-and-CPD</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/knowledge-transfer" title="Knowledge transfer">Knowledge transfer</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/knowledge-transfer/knowledge-transfer-partnerships" title="Knowledge Transfer Partnerships">Knowledge Transfer Partnerships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/technology" title="Technology transfer">Technology transfer</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/technology/current-projects" title="Current projects">Current projects</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/consultancy" title="Consultancy">Consultancy</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/consultancy/funding" title="Funding">Funding</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/consultancy/case-studies-nightingale-schools" title="Improved Learning Through Classroom Design ">Improved Learning Through Classroom Design </a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/facilities" title="Facilities">Facilities</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices" title="Conference services">Conference services</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2" title="Venues">Venues</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2/mediacityuk" title="MediaCityUK">MediaCityUK</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2/meeting,-lecture-and-board-rooms" title="Meeting, Lecture and Board Rooms">Meeting, Lecture and Board Rooms</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2/large-halls" title="Large Halls">Large Halls</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2/thinklab" title="THINKlab">THINKlab</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/venues2/enquiry-form" title="Venue Enquiry">Venue Enquiry</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/summer-bookings" title="Summer bookings">Summer bookings</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/testimonials" title="Testimonials">Testimonials</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/catering" title="Catering">Catering</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/conferenceservices/location" title="Location">Location</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students" title="Recruiting students">Recruiting students</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment" title="Recruitment fairs">Recruitment fairs</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/part-time-jobs-and-volunteering-work-fair" title="Part-time Jobs and Volunteering Work Fair">Part-time Jobs and Volunteering Work Fair</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/nmsw-fair" title="School of Nursing, Midwifery, Social Work &amp; Social Sciences">School of Nursing, Midwifery, Social Work &amp; Social Sciences</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/environment-recruitment-fair" title="School of the Built Environment Recruitment Fair ">School of the Built Environment Recruitment Fair </a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/business-and-it-placement-and-graduate-recruitment-fair" title="Business, IT &amp; Law Recruitment Fair">Business, IT &amp; Law Recruitment Fair</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/science-engineering-fair" title="Computing, Science &amp; Engineering Recruitment Fair  ">Computing, Science &amp; Engineering Recruitment Fair  </a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/acoustics-event" title="Acoustics, Audio and Video Engineering Event ">Acoustics, Audio and Video Engineering Event </a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/health-fair" title="School of Health Sciences Careers Fair">School of Health Sciences Careers Fair</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/language-recruitment-fair" title="Language Recruitment Fair">Language Recruitment Fair</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/recruitment/built-environment-industry-insight" title="School of the Built Environment Industry Insight Event">School of the Built Environment Industry Insight Event</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/free-vacancy-service" title="Free vacancy service">Free vacancy service</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/business/employ-students/free-vacancy-service/Policy-on-Advertising-Opportunities-and-Information-July-2014-Employability-and-Engagement.pdf" title="Policy-on-Advertising-Opportunities-and-Information-July-2014-Employability-and-Engagement.pdf">Policy-on-Advertising-Opportunities-and-Information-July-2014-Employability-and-Engagement.pdf</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/assisted-recruitment" title="Assisted recruitment ">Assisted recruitment </a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/work-with-the-university" title="Work with The University">Work with The University</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/funded-student-and-graduate-internships" title="Funded student and graduate internships">Funded student and graduate internships</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/testimonials" title="Testimonials">Testimonials</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/employ-students/employer-feedback-form" title="Employer feedback form">Employer feedback form</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/business/news" title="Research News">Research News</a>
			</li>
						<li><a href="http://www.salford.ac.uk/business/events" title="Business Events">Business Events</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk" title="MediaCityUK">MediaCityUK</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/mediacityuk/about" title="About MediaCityUK">About MediaCityUK</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/study" title="Study">Study</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/mediacityuk/study/courses" title="Courses at MediaCityUK">Courses at MediaCityUK</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/study/facilities" title="Facilities">Facilities</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/research" title="Research and Innovation">Research and Innovation</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/mediacityuk/research/the-research-hotel" title="Adobe Research Hotel powered by HP &amp; NVIDIA">Adobe Research Hotel powered by HP &amp; NVIDIA</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/business-services" title="Business services">Business services</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/mediacityuk/business-services/adobe-partnership" title="Adobe Partnership">Adobe Partnership</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/business-services/knowledge-transfer-partnerships" title="Knowledge transfer partnerships">Knowledge transfer partnerships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue" title="Venue">Venue</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/mediacityuk/venue/about-the-venue" title="About the venue">About the venue</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/360" title="Virtual tour">Virtual tour</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/the-egg-suite-and-gallery" title="‘The Egg’ Suite and Gallery ">‘The Egg’ Suite and Gallery </a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/digital-performance-lab" title="Digital Performance Lab ">Digital Performance Lab </a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/creative-studio-spaces" title="Creative studio spaces">Creative studio spaces</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/meeting-lecture-and-board-rooms" title="Meeting, lecture and board rooms">Meeting, lecture and board rooms</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/conference-services" title="Conference services">Conference services</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/venue/enquiry-form" title="Venue enquiry">Venue enquiry</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/location" title="How to get here">How to get here</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/news" title="MediaCityUK News">MediaCityUK News</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/events" title="MediaCityUK Events">MediaCityUK Events</a>
			</li>
						<li><a href="http://www.salford.ac.uk/mediacityuk/contact-us" title="Contact us ">Contact us </a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni" title="One University - One Global Community">One University - One Global Community</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/alumni/home" title="Home">Home</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/alumni-online" title="Alumni online">Alumni online</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/alumni/alumni-online/alumni-benefits" title="Alumni benefits">Alumni benefits</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/alumni-online/volunteering" title="Volunteering">Volunteering</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/alumni-online/alumni-events" title="Alumni events">Alumni events</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/alumni-online/notable-alumni" title="Notable alumni">Notable alumni</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/alumni-online/alumni-achievement-awards-2015" title="Alumni Achievement Awards 2015">Alumni Achievement Awards 2015</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford" title="Giving to Salford">Giving to Salford</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/action-on-dementia" title="Salford Institute for Dementia">Salford Institute for Dementia</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/supporting-students" title="Supporting Students">Supporting Students</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/student-hardship" title="Student Hardship">Student Hardship</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/campus-initiatives" title="Campus Initiatives">Campus Initiatives</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/inspiring-salford" title="Inspiring Salford">Inspiring Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/give-online" title="Give online">Give online</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/giving-to-salford/donor-list-of-honour" title="Donor list of honour">Donor list of honour</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/university-events" title="University events">University events</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/arts" title="Arts">Arts</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/santander-universities-partnership" title="Santander Universities Partnership">Santander Universities Partnership</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/donate-now" title="Donate now">Donate now</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/contact-us" title="Contact us">Contact us</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/alumni/contact-us/privacy-policy" title="Privacy Policy">Privacy Policy</a>
			</li>
						<li><a href="http://www.salford.ac.uk/alumni/contact-us/unsubscribe-from-emails" title="Unsubscribe from emails">Unsubscribe from emails</a>
			</li>
					</ul>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us" title="About the University of Salford">About the University of Salford</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/heritage" title="Heritage">Heritage</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information" title="Corporate information">Corporate information</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/governance" title="Governance">Governance</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/governance/annual-report-and-financial-statements" title="Annual report and financial statements">Annual report and financial statements</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/governance/policies-and-procedures" title="Policies &amp; Procedures">Policies &amp; Procedures</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/governance/wis" title="The Wider Information Set">The Wider Information Set</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus" title="Our developing campus">Our developing campus</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/benefits-for-salford" title="Benefits for Salford">Benefits for Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/new-adelphi" title="New Adelphi Building">New Adelphi Building</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/chapman-refurbishment" title="Chapman refurbishment">Chapman refurbishment</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/public-spaces" title="Public spaces">Public spaces</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/student-village" title="Student residences">Student residences</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/faq" title="FAQ">FAQ</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/our-developing-campus/other-developments" title="Other developments">Other developments</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships" title="Partnerships">Partnerships</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/uk-partnerships" title="UK Partnerships">UK Partnerships</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/who-we-are" title="Who we are">Who we are</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/what-we-do" title="What we do">What we do</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/what-we-do/staff-development-for-partners" title="Staff development for partners">Staff development for partners</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/uk-partner-profiles" title="UK partner profiles">UK partner profiles</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/partnerships/contact-uk-partnerships" title="Contact UK Partnerships">Contact UK Partnerships</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/strategy" title="Strategy">Strategy</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/__data/assets/image/0003/491241/university-of-salford-strategic-plan-cover.jpg" title="university-of-salford-strategic-plan-cover.jpg">university-of-salford-strategic-plan-cover.jpg</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/university-structure" title="University structure">University structure</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/university-structure/leadership-and-management" title="Leadership and Management">Leadership and Management</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/university-structure/leadership-and-management/dr-irene-khan" title="Dr Irene Khan">Dr Irene Khan</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/university-structure/schools-and-colleges" title="Schools and Colleges">Schools and Colleges</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/university-structure/professional-services" title="Professional Services">Professional Services</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity" title="Corporate identity">Corporate identity</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/marketing-support" title="Marketing support">Marketing support</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/toolkit" title="Toolkit">Toolkit</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/merchandise" title="Merchandise">Merchandise</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/use-of-the-logo" title="Use of the logo">Use of the logo</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/photography-and-filming" title="Photography &amp; filming ">Photography &amp; filming </a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/social-media-guidelines" title="Social media guidelines ">Social media guidelines </a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/style-guide" title="Style guide">Style guide</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/faq" title="FAQ">FAQ</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/corporate-identity/key-contacts" title="Key contacts">Key contacts</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/corporate-information/press-office" title="Press Office">Press Office</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community" title="Community engagement">Community engagement</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/community/community-university-partnerships" title="Community-University Partnerships">Community-University Partnerships</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/harold-riley-award" title="Harold Riley Award">Harold Riley Award</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/community/harold-riley-award/2012-winners" title="2012 Winners">2012 Winners</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/harold-riley-award/runners-up" title="Runners Up">Runners Up</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/student-volunteering" title="Student Volunteering">Student Volunteering</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/supporting-charities" title="Supporting Charities">Supporting Charities</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/community-benefits-through-procurement" title="Community Benefits through Procurement">Community Benefits through Procurement</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/community/news" title="Community News">Community News</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/environmental-sustainability" title="Environmental sustainability">Environmental sustainability</a>
					<ul>
			<li><a href="http://www.salford.ac.uk/about-us/environmental-sustainability/zero-emissions-car-trial" title="Zero emissions car trial">Zero emissions car trial</a>
			</li>
					</ul>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/life-at-salford" title="Life at Salford">Life at Salford</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/events" title="Events">Events</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/jobs" title="Jobs">Jobs</a>
			</li>
						<li><a href="http://www.salford.ac.uk/about-us/travel" title="How to find us">How to find us</a>
		
			</li>
					</ul>
			</li>
					</ul>
            
            
            
            
            
            
            
        </div>           
    </div>
    
    
    

</div>
<!-- /container -->                        
                        

<?php require('template/footer.phtml') ?>
