<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">	
                <div class="col-md-4 widget">
                    <h3 class="widget-title">Links</h3>
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="index.php">Home</a><br>
                            <a href="about.php">About</a><br>
                            <a href="msccourses.php">MSc Courses</a><br>
                            <a href="mediacity.php">Media City</a><br>
                            <a href="international.php">International</a><br>
                            <a href="contact.php">Contact Us</a><br>
                            <strong><a href="http://sgh970.mit12.csesalford.com/Moodle/login/index.php" target="blank">Login</a></strong>
                        </p>
                    </div>
                </div>

                <div class="col-md-4 widget">
                    <h3 class="widget-title">Follow me</h3>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href="https://www.facebook.com/CSSalford" target="_blank"><i class="fa fa-facebook fa-2"></i></a>
                            <a href="https://twitter.com/CSSalford" target="_blank"><i class="fa fa-twitter fa-2"></i></a>
                        </p><br><br><br>
                        <img src="images/qaa.png" alt="QAA">
                    </div>
                </div>

                <div class="col-md-4 widget">
                    <h3 class="widget-title">Contact</h3>
                    <div class="widget-body">
                        <p>The University of Salford <br>
                            The Crescent<br> 
                            Salford <br> 
                            M5 4WT<br> 
                            UK <br><br>
                            0161 295 5000
                        </p>	
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">	
                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="sitemap.php">Site Map</a> | 
                            <a href="accessibility.php">Accessibility</a> |
                            <a href="privacypolicy.php">Privacy Policy</a> |
                            <a href="foi.php">FOI Request</a>

                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            &copy; University of Salford 2015
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>	

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="js/headroom.min.js"></script>
<script src="js/jQuery.headroom.min.js"></script>
<script src="js/template.js"></script>


</body>
</html>